package BattleShipGameApplication;

import Misc.Constants;
import BattleShip.*;
import Misc.MessageBox;
import gameengine.GameException;
import java.awt.Color;
import java.awt.Component;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

public class FrameMainMenu extends javax.swing.JFrame
{
    MainPanel1 pnlMainPanel1 = new MainPanel1();
    MainPanel2 pnlMainPanel2 = new MainPanel2();
    public FrameMainMenu()
    {
        setContentPane(new JLabel(new ImageIcon("Assets\\MainMenuBackground.jpg")));
        initComponents();
        GameEngine.InitSettings();
        pnlMainPanel.setBackground(new Color(0, 0, 0, 0));
        pnlMainPanel.add(pnlMainPanel1);
        pnlMainPanel.add(pnlMainPanel2);
        DisplayMainPanel1();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        pnlMainPanel = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(512, 512));
        setUndecorated(true);
        setResizable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 492, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(151, Short.MAX_VALUE)
                .addComponent(pnlMainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel pnlMainPanel;
    // End of variables declaration//GEN-END:variables
    public void DisplayMainPanel1()
    {
        setVisible(true);
        pnlMainPanel.getComponent(1).setVisible(false);
        pnlMainPanel.getComponent(0).setVisible(true);
        UpdateFrame();
    }
    public void DisplayMainPanel2()
    {
        setVisible(true);
        pnlMainPanel.getComponent(1).setVisible(true);
        pnlMainPanel.getComponent(0).setVisible(false);
        ((MainPanel2) pnlMainPanel.getComponent(1)).FillSettings();
        UpdateFrame();
    }
    private void UpdateFrame()
    {
        pnlMainPanel.setBackground(new Color(0, 0, 0, 0));
        pnlMainPanel.repaint();
        repaint();
    }
    public void Exit()
    {
        dispose();
        System.exit(0);
    }
}
